###
# Build Image
###
FROM node:22-alpine AS build

WORKDIR /srv/strapi

COPY ./src/ .

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

RUN yarn install --frozen-lockfile
RUN yarn build

###
# Production Image
###
FROM node:22-alpine

WORKDIR /srv/strapi

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
ENV PATH=/srv/strapi/node_modules/.bin:$PATH

COPY --from=build /srv/strapi/ ./

RUN chown -R node:node ./

USER node
EXPOSE 1337

CMD ["yarn", "start"]
